name: Dash Visualization

on:
  push:
    branches:
      - master

jobs:
  run-dash:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Dash app
      run: python app.py
