name: Update Data

on:
  push:
    branches: 
      - mater

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt
    - name: Run Script
      run: python .github/workflows/app.py
    - name: Commit Changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: hello
        author_email: 746141186@qq.com
        message: "Update data"
        add: 'json/实时.json'
        token: ${{ secrets.ACCESS_TOKEN }}
