name: Update data

on:
  push:
    branches:
      - master

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update data
        run: python app.py
        env:
          GITHUB_TOKEN: ${{ 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 }}
