name: Web Scraping

on:
  push:
    branches:
      - master

jobs:
  run-scraping:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run web scraping
      run: python app.py
    - name: Save dict to file
      run: |
        mkdir -p data
        mv 实时.json json/
